const microbenchMeaning = {
    "cca": "Completely Biased Branch",
    "cce": "Easy to predict Control Flow (alternating branches)",
    "cch": "Impossible to predict control",
    "cch_st": "Impossible to predict control + interaction with stores",
    "ccm": "Heavily Biased Branches",
    "cci": "Impossible control with large basic blocks (potentially larger penalty)",
    "cf1": "Inlining Test for functions containing loops",
    "crd": "Recursive Control Flow -- 1000 Deep",
    "crf": "Recursive Control Flow -- Fibonacci",
    "crm": "Merge sort",
    "cs1": "Switch Case Statement of size 10 -- Different Case each time",
    "cs3": "Switch Case Statement of Size 10 -- Different case every third time",
    "dp1d": "Simple Data Parallel Loop - Double Arithmetic",
    "dp1f": "Simple Data Parallel Loop - Float Arithmetic",
    "dpt": "Simple Data Parallel Loop -- sin() computation",
    "dptd": "Simple Data Parallel Loop -- double sin() computation",
    "dpcvt": "Simple Data Parallel Loop -- Simple Data Parallel Loop Float/Double Conversion",
    "ed1": "Integer Execution -- Length 1 Dependency Chain per Iteration",
    "ef": "Floating-point Execution -- 8 Independent instructions per Iteration",
    "ei": "Integer Execution -- 8 Independent computations per iteration",
    "em1": "Integer Execution -- Length 1 Dependency Chain each loop (with multiplies)",
    "em5": "Integer Execution -- Length 5 Dependency Chain each loop (with multiplies)",
    "mc": "Conflict Misses (tune to your cache arch. by adding more streams)",
    "mcs": "Confict Misses with Stores (tune to your cache arch)",
    "md": "Cache resident Linked List Traversal",
    "mi": "8 Streams of independent memory access, all cache resident",
    "mim": "8 Streams independent memory access, no conflicts",
    "mim2": "8 Streams independent Memory Access -- 2 coalescing ops per iteration",
    "mip": "Large Instruction Region -- Instruction cache Misses",
    "ml2": "L2 resident (depending on LFSR settings) linked list traversal",
    "ml2_bw_ld": "L2 Resident linked list traversal -- B/W limited (loads)",
    "ml2_bw_st": "L2 Resident linked list traversal -- B/W limited (stores)",
    "ml2_bw_ldst": "L2 Resident linked list traversal -- B/W limited (loads and stores)",
    "ml2_st": "L2 resident linked list traversal (stores)",
    "mm": "Non-cache resident linked-list traversal",
    "mm_st": "Non-cache resident linked-list traversal (stores)",
    "m": "Load Store Access with Differing dynamic dependencies",
    "stl2": "Repeatedly store, L2 Cache Resident",
    "stl2b": "Repeatedly Store, L2 Resident (occasional stores)",
    "stc": "Repeatedly Store in consecutive access - L1 Cache"
};

export default microbenchMeaning;

